### ISSUE TITLE
Section 65 got lost.

### ISSUE THREAD

**Issue by ascherer** [igor-liferenko/dvitype#4]
`cdvitype.patch` tries to be clever when initializing `default_directory` in section 64, but **Section 65** of `dvitype.web` gets lost in `dvitype.w` und so the section numbering differs between the two variants.

Its good **C/WEB** practice to keep the section numbering up to “System-dependent changes” (or the “Index”) intact.

[At least there should be a dummy **Section 65** that points to section 64.]

**Comment by igor-liferenko** [comment]
Closed in commits 15703 and c3f84.
